const fs = require("fs");
const path = require("path");

const root = __dirname;
const source = path.join(root, "supabase-app");
const target = path.join(root, "dist");
const supabaseUrl = String(process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || "").trim();
const supabaseAnonKey = String(process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "").trim();

fs.rmSync(target, { recursive: true, force: true });
fs.mkdirSync(target, { recursive: true });

function copyRecursive(fromDir, toDir) {
  fs.mkdirSync(toDir, { recursive: true });
  for (const entry of fs.readdirSync(fromDir, { withFileTypes: true })) {
    const from = path.join(fromDir, entry.name);
    const to = path.join(toDir, entry.name);
    if (entry.isDirectory()) {
      copyRecursive(from, to);
      continue;
    }
    if (!entry.isFile()) continue;
    fs.copyFileSync(from, to);
  }
}

copyRecursive(source, target);

fs.writeFileSync(path.join(target, "supabase-config.js"), [
  "// Generated by Vercel during build from this project's environment variables.",
  `export const SUPABASE_URL = ${JSON.stringify(supabaseUrl)};`,
  `export const SUPABASE_ANON_KEY = ${JSON.stringify(supabaseAnonKey)};`,
  "",
].join("\n"));

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn("Vercel build warning: SUPABASE_URL or SUPABASE_ANON_KEY is missing. The app still deployed, but it will need Vercel environment variables before it can connect to Supabase.");
} else {
  console.log("Vercel build ready: copied supabase-app to dist and generated Supabase config from environment variables.");
}
