create table if not exists public.trucking_requests (
  id bigserial primary key,
  request_no text unique not null,
  request_date date,
  customer text,
  project text,
  jobsite text,
  needed_date date,
  requested_by text,
  requestor_email text,
  po_no text,
  status text default 'Requested',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.trucking_request_lines (
  id bigserial primary key,
  request_no text references public.trucking_requests(request_no) on delete cascade,
  line_no integer not null,
  asset_source text,
  asset_tag text,
  equipment_label text,
  service text,
  origin text,
  destination text,
  notes text,
  status text default 'Requested',
  ticket_no text,
  created_at timestamptz default now(),
  unique(request_no, line_no)
);

create table if not exists public.trucking_moves (
  id bigserial primary key,
  ticket_no text unique not null,
  request_no text,
  request_line_no integer,
  move_date date,
  customer text,
  project text,
  jobsite text,
  requested_by text,
  po_no text,
  asset_source text,
  asset_tag text,
  equipment_label text,
  service text,
  rate numeric default 0,
  rate_type text,
  amount numeric default 0,
  origin text,
  destination text,
  driver_name text,
  driver_email text,
  start_time time,
  end_time time,
  container_no text,
  seal_no text,
  vessel_voyage text,
  bl_no text,
  truck_license text,
  chassis_no text,
  bin_status text,
  customer_print text,
  driver_print text,
  customer_signature text,
  driver_signature text,
  notes text,
  status text default 'Scheduled',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.trucking_rates (
  id bigserial primary key,
  service text unique not null,
  rate numeric default 0,
  rate_type text,
  additional text,
  category text default 'Service',
  status text default 'Active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

insert into public.trucking_rates(service, rate, rate_type, additional, category, status) values
('End Dump', 125, 'Hourly', '', 'Service', 'Active'),
('Sidelifter', 650, 'Flat Rate', '', 'Service', 'Active'),
('Lowboy', 200, 'Hourly', '', 'Service', 'Active'),
('Rolloff Bin Service', 195, 'Flat Rate', 'Add Tipping Fee', 'Service', 'Active'),
('Rolloff Flat Rack Service', 85, 'Hourly', '', 'Service', 'Active'),
('Peterbilt RollOff', 85, 'Hourly', '', 'Service', 'Active'),
('Commercial Tractor', 125, 'Hourly', '', 'Service', 'Active'),
('Dump Truck', 85, 'Hourly', '', 'Service', 'Active'),
('Water Truck', 550, 'Flat Rate', '', 'Service', 'Active'),
('PUMP TRUCK', 185, 'Flat Rate', '', 'Service', 'Active'),
('Vacall', 180, 'Flat Rate', '', 'Service', 'Active'),
('Back Hoe', 135, 'Hourly', '', 'Service', 'Active'),
('TL4607 F150', 60, 'Hourly', '', 'Service', 'Active'),
('Lowboy Rental', 1000, 'Daily', '', 'Service', 'Active'),
('AECOM Pump', 350, 'Flat Rate', '', 'Service', 'Active'),
('BL Harbert Pump', 350, 'Flat Rate', '', 'Service', 'Active'),
('Amentum Pump', 350, 'Flat Rate', '', 'Service', 'Active'),
('Sidelifter-double wide', 5000, 'Flat Rate', '', 'Service', 'Active'),
('Street Sweeper', 85, 'Hourly', '', 'Service', 'Active'),
('StakeTruck', 85, 'Hourly', '', 'Service', 'Active'),
('operate', 50, 'Hourly', '', 'Service', 'Active'),
('Flatrack/Chameleon', 85, 'Hourly', '', 'Service', 'Active'),
('Highbed/Chameleon', 85, 'Hourly', '', 'Service', 'Active'),
('Keevac', 185, 'Flat Rate', '', 'Service', 'Active'),
('0-1,000 gallon', 400, 'Flat Rate', '', 'Fuel/Water', 'Active'),
('1,000-2,500 gallon', 750, 'Flat Rate', '', 'Fuel/Water', 'Active'),
('2,500-4,000 gallon', 1000, 'Flat Rate', '', 'Fuel/Water', 'Active'),
('Clean Wood Debris', 15, '/cy', '', 'Tipping Fee', 'Active'),
('Green Waste', 15, '/cy', '', 'Tipping Fee', 'Active'),
('Construction Debris', 30, '/cy', '', 'Tipping Fee', 'Active'),
('Mixed Debris', 20, '/cy', '', 'Tipping Fee', 'Active'),
('Metals', 15, '/cy', '', 'Tipping Fee', 'Active'),
('Corrugated Board', 15, '/cy', '', 'Tipping Fee', 'Active'),
('Grainger', 386.63, '/ton', '', 'Tipping Fee', 'Active'),
('None', 0, '/cy', '', 'Tipping Fee', 'Active'),
('BRPH', 386.63, '/ton', '', 'Tipping Fee', 'Active'),
('ECC', 35, '/cy', '', 'Tipping Fee', 'Active'),
('EDCH', 35, '/cy', '', 'Tipping Fee', 'Active'),
('Rubbishman', 386.63, '/ton', '', 'Tipping Fee', 'Active'),
('UMS', 35, '/cy', '', 'Tipping Fee', 'Active')
on conflict (service) do update set
  rate = excluded.rate,
  rate_type = excluded.rate_type,
  additional = excluded.additional,
  category = excluded.category,
  status = excluded.status,
  updated_at = now();

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.trucking_requests, public.trucking_request_lines, public.trucking_moves, public.trucking_rates to authenticated;
grant select, insert, update on table public.trucking_requests, public.trucking_request_lines, public.trucking_moves to anon;
grant select on table public.trucking_rates to anon;
grant usage, select on all sequences in schema public to anon, authenticated;
